apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vertical-marsupial-java-quarkus
  janus-idp.io/tekton: vertical-marsupial-java-quarkus
  backstage.io/kubernetes-id: vertical-marsupial-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: vertical-marsupial-java-quarkus
resources: 
- deployment.yaml
- route.yaml
- service.yaml
